# Generated by Django 5.2.8 on 2025-11-14 23:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('oracle', 'Oracle'), ('sqlserver', 'Microsoft SQL Server'), ('sqlite', 'SQLite')], max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('dbname', models.CharField(max_length=255, verbose_name='Database Name')),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='database', to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_tables', to='main.project')),
            ],
            options={
                'unique_together': {('project', 'table_name')},
            },
        ),
    ]
