# Generated by Django 5.2.8 on 2025-11-15 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('column_name', models.CharField(max_length=255)),
                ('column_type', models.CharField(choices=[('datetime', 'Datetime'), ('numeric', 'Numeric')], max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='main.project')),
            ],
            options={
                'unique_together': {('project', 'table_name', 'column_name')},
            },
        ),
    ]
