# Generated by Django 5.2.8 on 2025-11-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_trainingsession_trainingdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='task_id',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
