# Generated by Django 5.2.8 on 2025-11-16 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_task_id_to_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions_as_model', to='main.model'),
        ),
    ]
