# Generated by Django 5.2.8 on 2025-11-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_model_to_trainingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcolumn',
            name='column_type',
            field=models.CharField(choices=[('datetime', 'Datetime'), ('numeric', 'Numeric'), ('multigroup', 'Multigroup')], max_length=50),
        ),
    ]
