# Generated by Django 5.2.8 on 2025-11-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_projectcolumn_column_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='group_columns',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
