# Generated by Django 5.2.8 on 2025-11-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_model_group_name_trainingsession_group_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='main.trainingsession'),
        ),
    ]
