# Generated by Django 5.2.8 on 2025-11-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_model_training_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='numeric_columns',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
